	LJMP	START
	ORG	100H
START:
	LCALL LCD_CLR
	LCALL WAIT_KEY
	MOV R1,A ;pobranie pierwszej liczby
	LCALL TO_BCD
	LCALL WRITE_HEX
	LCALL WAIT_KEY
	MOV R2,A  ;pobranie drugiej liczby
	LCALL TO_BCD
	LCALL WRITE_HEX
	LCALL WAIT_KEY

	CJNE A,#10,ODEJM ; SPRAWD� CZY DODAWANIE (podajemy pierwszą i drugą liczbę i jak klkniemy A 
	MOV A,#'+'; JEST DODAWANIE
	LCALL WRITE_DATA
	MOV A,#'=';
	LCALL WRITE_DATA
	MOV A,R1
	ADD A,R2
	MOV R3,A
	LCALL TO_BCD
	LCALL WRITE_HEX
	MOV A,#20
	LCALL DELAY_100MS
ODEJM:
	CJNE A,#11,MNOZ; SPRAWD� CZY ODEJMOWANIE
	; WYKONAJ ODEJMOWANIE I ZAPISZ WYNIK
	MOV A,#'-' ; JEST ODEJMOWANIE
	LCALL WRITE_DATA
	MOV A,#'=' ; JEST ODEJMOWANIE
	LCALL WRITE_DATA
	MOV A,R1
	CLR C;
	SUBB A,R2
	MOV R3,A
	LCALL TO_BCD
	LCALL WRITE_HEX
	MOV A,#20
	LCALL DELAY_100MS
MNOZ:
	CJNE A,#12,DZIEL; SPRAWD� CZY MNO�ENIE
	; WYKONAJ MNO�ENIE I ZAPISZ WYNIK
	MOV A,#'X' ; JEST MNO�ENIE
	LCALL WRITE_DATA
	MOV A,#'=' ; JEST MNO�ENIE
	LCALL WRITE_DATA
	MOV A,R1
	MOV B,R2
	MUL AB
	MOV R3,A
	MOV R4,B
	MOV A,R3
	LCALL WRITE_HEX
	MOV A,R4
	LCALL WRITE_HEX
	MOV A,#20
	LCALL DELAY_100MS
DZIEL:
	CJNE A,#13,START; SPRAWD� CZY MNO�ENIE
	; WYKONAJ DZIELENIE I ZAPISZ WYNIK
	MOV A,#'/' ; JEST DZIELENIE
	LCALL WRITE_DATA
	MOV A,#'=' ; JEST MNO�ENIE
	LCALL WRITE_DATA
	MOV A,R1
	MOV B,R2
	DIV AB		;W A MAMY CA�OWCI A W B RESZTE Z DZIELENIA
	MOV R3,A
	MOV R4,B
	LCALL TO_BCD
	LCALL WRITE_HEX
	MOV A,#'_' ; JEST DZIELENIE
	LCALL WRITE_DATA
	MOV A,R4
	LCALL TO_BCD
	LCALL WRITE_HEX
	MOV A,#'/' ; JEST DZIELENIE
	LCALL WRITE_DATA
	MOV A,R2
	LCALL TO_BCD
	LCALL WRITE_HEX
	MOV A,#20
	LCALL DELAY_100MS



WYSW_ZNAK:
	LCALL WRITE_DATA
	RET



STOP:			;nie wykonuj innych dzia�a�
	LJMP	STOP	;- pozosta� w p�tli STOP
	NOP
	
TO_BCD:
	;ZAMIANA NA BCD -POCZ�TEK
	MOV B,#10; DZIELNIK
	DIV AB; WYDZIELAMY CYFRE DZIESIATEK
	ORL A,B; DODAJEMY CYFR� JEDNO�CI
	;ZAMIANA NA BCD -KONIEC
	RET
	NOP
