	LJMP	START
	ORG	100H

START:

  LCALL LCD_CLR      ;             Wyzeruj wyswietlacz

	;*************************  1 LICZBA
  LCALL WAIT_KEY
	PUSH ACC            ;        ZAPISUJEMY LICZB� NA STOSIE
      	;ZAMIANA NA BCD - POCZ�TEK
	MOV B,#10     ; DZIELNIK
	DIV AB; WYDZIELAMY CYFRE DZIESIATEK
	SWAP A; PRZESUWAMY CYFR� DZIESI�TEK NA WYZSZY 4 BITY
	ORL A,B; DODAJEMY CYFR� JEDNOS?CI
    	; ZAMIANA NA BCD - KONIEC
	LCALL WRITE_HEX; WYSWIETLANIE LICZBY

	  ;WYSWIETLANIE SPACJI
	  MOV  A,#' '
	  LCALL WRITE_DATA
   

  ; ***********************  WPISANIE 2 LICZBY
  LCALL WAIT_KEY
	PUSH ACC
	MOV B,#10
	DIV AB
	SWAP A
	ORL A,B
	LCALL WRITE_HEX
	MOV A,#' '
	LCALL WRITE_DATA

    ;******  WYBOR OPERACJI

    LCALL WAIT_KEY
    CJNE A,#10,ODEJM ; SPRAWD� CZY DODAWANIE
    ; WYKONAJ DODAWANIE

    POP 07H
    POP ACC
    ADD A,R7

     PUSH ACC
     MOV B,#10; DZIELNIK
    	DIV AB; WYDZIELAMY CYFRE DZIESIATEK
	   SWAP A; PRZESUWAMY CYFR� DZIESI�TEK NA WY�SZY 4 BITY
	   ORL A,B; DODAJEMY CYFR� JEDNO?CI
	  ;ZAMIANA NA BCD - KONIEC
   	LCALL WRITE_HEX; WYSWIETLANIE LICZBY
     MOV      A,#20            ; do akumulatora dodajemy mnoznik =20
     LCALL    DELAY_100MS     ; OPOZNIENIE O 100MS * 20


ODEJM:
   CJNE A,#11,MNOZ
     ; WYKONAJ ODEJMOWANIE

     POP 07H
	   POP ACC
	   CLR C
	   SUBB A,R7
	   PUSH ACC
     MOV B,#10; DZIELNIK
   	DIV AB; WYDZIELAMY CYFRE DZIESIATEK
	  SWAP A; PRZESUWAMY CYFR� DZIESI�TEK NA WY�SZY 4 BITY
	  ORL A,B; DODAJEMY CYFR� JEDNO?CI
	 ;ZAMIANA NA BCD - KONIEC
   	LCALL WRITE_HEX; WYSWIETLANIE LICZBY
   	    MOV      A,#20            ; do akumulatora dodajemy mnoznik =20
   LCALL    DELAY_100MS     ; OPOZNIENIE O 100MS * 20


MNOZ:
      CJNE A,#12,DZIEL

	; WYKONAJ MNO�ENIE I ZAPISZ WYNIK
	POP B
	POP ACC
	MUL AB
	MOV 04H,B
	PUSH ACC
	LCALL WRITE_HEX; WYSWIETLANIE LICZBY
  	LCALL WAIT_KEY


   ;MOV      A,#20            ; do akumulatora dodajemy mnoznik =20
  ; LCALL    DELAY_100MS     ; OPOZNIENIE O 100MS * 20

DZIEL:
  CJNE A,#13,START

	POP B
	MOV 05H,B
	POP ACC
	DIV AB
	PUSH B
	MOV B,#10
	DIV AB
	SWAP A
	ORL A,B
	PUSH ACC

	MOV A,#'='
        LCALL WRITE_DATA
	MOV A,#' '
	LCALL WRITE_DATA
	POP ACC
	LCALL WRITE_HEX
	MOV A,#' '
	LCALL WRITE_DATA
	POP ACC
	LCALL WRITE_HEX
	MOV A,#'/'
	LCALL WRITE_DATA
	MOV A,05H
	MOV B,#10; DZIELNIK
	DIV AB; WYDZIELAMY CYFRE DZIESIATEK
	SWAP A; PRZESUWAMY CYFR� DZIESI�TEK NA WY�SZY 4 BITY
	ORL A,B; DODAJEMY CYFR� JEDNO?CI
	;ZAMIANA NA BCD - KONIEC
	LCALL WRITE_HEX
	LCALL WAIT_KEY


;	LCALL WRITE_HEX; WYSWIETLANIE LICZBY
  ; MOV      A,#20            ; do akumulatora dodajemy mnoznik =20
  ; LCALL    DELAY_100MS     ; OPOZNIENIE O 100MS * 20





 LJMP   START
         NOP
